import NextAuth from "next-auth";
import { PrismaAdapter } from "@auth/prisma-adapter";
import Credentials from "next-auth/providers/credentials";
import Google from "next-auth/providers/google";
import crypto from "crypto";
import bcrypt from "bcryptjs";
import { prisma } from "@/lib/db";
import { verifyTurnstile } from "@/lib/turnstile";

/** Verify the HMAC bypass token generated by accept-invite. Checks current and previous minute windows. */
function verifySigninBypass(email: string, bypassToken: string): boolean {
  const secret = process.env.AUTH_SECRET || process.env.NEXTAUTH_SECRET;
  // No secret configured -> disable the bypass entirely (fail closed). An empty
  // HMAC key is attacker-known, so a "" fallback would let anyone forge a valid
  // Turnstile-bypass token.
  if (!secret) return false;
  const now = Math.floor(Date.now() / 60_000);
  for (const window of [now, now - 1]) {
    const expected = crypto.createHmac("sha256", secret).update(`${email}|${window}`).digest("hex");
    if (crypto.timingSafeEqual(Buffer.from(expected), Buffer.from(bypassToken))) return true;
  }
  return false;
}

export const { handlers, auth, signIn, signOut } = NextAuth({
  trustHost: true,
  adapter: PrismaAdapter(prisma),
  session: { strategy: "jwt" },
  pages: {
    signIn: "/auth/sign-in",
  },
  cookies: {
    sessionToken: {
      name: "__Secure-next-auth.session-token",
      options: {
        httpOnly: true,
        sameSite: "lax",
        path: "/",
        secure: true,
        domain: ".vanguardm.com",
      },
    },
    csrfToken: {
      name: "__Host-next-auth.csrf-token",
      options: {
        httpOnly: true,
        sameSite: "lax",
        path: "/",
        secure: true,
      },
    },
    pkceCodeVerifier: {
      name: "next-auth.pkce.code_verifier",
      options: {
        httpOnly: true,
        sameSite: "lax",
        path: "/",
        secure: true,
        domain: ".vanguardm.com",
        maxAge: 900, // 15 minutes
      },
    },
    state: {
      name: "next-auth.state",
      options: {
        httpOnly: true,
        sameSite: "lax",
        path: "/",
        secure: true,
        domain: ".vanguardm.com",
        maxAge: 900,
      },
    },
    callbackUrl: {
      name: "next-auth.callback-url",
      options: {
        httpOnly: true,
        sameSite: "lax",
        path: "/",
        secure: true,
        domain: ".vanguardm.com",
      },
    },
  },
  providers: [
    // Only register Google if credentials are configured
    ...(process.env.GOOGLE_CLIENT_ID && process.env.GOOGLE_CLIENT_SECRET
      ? [
          Google({
            clientId: process.env.GOOGLE_CLIENT_ID,
            clientSecret: process.env.GOOGLE_CLIENT_SECRET,
            allowDangerousEmailAccountLinking: true,
          }),
        ]
      : []),
    Credentials({
      name: "credentials",
      credentials: {
        email: { label: "Email", type: "email" },
        password: { label: "Password", type: "password" },
        turnstileToken: { label: "Turnstile Token", type: "text" },
        bypassToken: { label: "Bypass Token", type: "text" },
      },
      async authorize(credentials) {
        if (!credentials?.email || !credentials?.password) return null;

        // Accept HMAC bypass token from invite acceptance (skips Turnstile)
        const bypass = credentials.bypassToken as string | undefined;
        const hasBypass = bypass && bypass.length === 64 &&
          verifySigninBypass(credentials.email as string, bypass);

        // Verify Turnstile — reject if configured but token missing (unless bypassed)
        if (!hasBypass) {
          const turnstileKey = process.env.TURNSTILE_SECRET;
          const token = credentials.turnstileToken as string | undefined;
          if (turnstileKey) {
            if (!token) return null;
            const valid = await verifyTurnstile(token);
            if (!valid) return null;
          }
        }

        const user = await prisma.user.findUnique({
          where: { email: credentials.email as string },
          include: { agency: { select: { slug: true } } },
        });
        if (!user || !user.password) return null;

        // Check account lockout
        if (user.lockedUntil && user.lockedUntil > new Date()) return null;

        const isValid = await bcrypt.compare(
          credentials.password as string,
          user.password,
        );
        if (!isValid) {
          const attempts = user.failedLoginAttempts + 1;
          const data: Record<string, unknown> = { failedLoginAttempts: attempts };
          if (attempts >= 5) data.lockedUntil = new Date(Date.now() + 15 * 60 * 1000);
          await prisma.user.update({ where: { id: user.id }, data });
          return null;
        }

        const agency = user.agency;

        // Reset lockout counter on successful login. Roles come from the stored
        // user record (set at invite acceptance) — never derived from email.
        await prisma.user.update({
          where: { id: user.id },
          data: { failedLoginAttempts: 0, lockedUntil: null },
        });

        return {
          id: user.id,
          name: user.name,
          email: user.email,
          image: user.image,
          isAdmin: user.isAdmin,
          role: user.role,
          clientId: user.clientId,
          portalOnboarded: user.portalOnboarded,
          agencyId: user.agencyId,
          agencySlug: agency?.slug ?? null,
        };
      },
    }),
  ],
  callbacks: {
    async jwt({ token, user, trigger }) {
      if (user) {
        token.id = user.id;
        token.isAdmin = (user as Record<string, unknown>).isAdmin ?? false;
        token.role = (user as Record<string, unknown>).role ?? "USER";
        token.clientId = (user as Record<string, unknown>).clientId ?? null;
        token.portalOnboarded = (user as Record<string, unknown>).portalOnboarded ?? false;
        token.agencyId = (user as Record<string, unknown>).agencyId ?? null;
        token.agencySlug = (user as Record<string, unknown>).agencySlug ?? null;
      }
      // Refresh portalOnboarded from DB when session is updated (after onboarding)
      if (trigger === "update" && token.id) {
        const dbUser = await prisma.user.findUnique({
          where: { id: token.id as string },
          select: { portalOnboarded: true },
        });
        if (dbUser) token.portalOnboarded = dbUser.portalOnboarded;
      }
      // Backfill agencySlug for tokens created before it was added
      if (token.agencyId && !token.agencySlug) {
        const agency = await prisma.agency.findUnique({
          where: { id: token.agencyId as string },
          select: { slug: true },
        });
        if (agency) token.agencySlug = agency.slug;
      }
      return token;
    },
    async session({ session, token }) {
      if (token?.id) {
        session.user.id = token.id as string;
        session.user.isAdmin = token.isAdmin as boolean;
        session.user.role = (token.role as "ADMIN" | "TEAM" | "USER" | "CLIENT") ?? "USER";
        session.user.clientId = (token.clientId as string) ?? null;
        session.user.portalOnboarded = (token.portalOnboarded as boolean) ?? false;
        session.user.agencyId = (token.agencyId as string) ?? null;
        session.user.agencySlug = (token.agencySlug as string) ?? null;
      }
      return session;
    },
  },
});
